USER-SUPPLIED VALUES:
controllers:
  main:
    containers:
      main:
        env:
          PGID: "1000"
          PUID: "1000"
          TZ: Europe/London
        image:
          repository: linuxserver/sonarr
          tag: latest
    pod:
      dnsConfig:
        options:
        - name: single-request-reopen
        - name: ndots
          value: "1"
        - name: timeout
          value: "1"
        - name: attempts
          value: "2"
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    strategy: Recreate
persistence:
  config:
    accessMode: ReadWriteOnce
    globalMounts:
    - path: /config
    size: 5Gi
    storageClass: local-path
    type: persistentVolumeClaim
  downloads:
    globalMounts:
    - path: /downloads
    hostPath: /mnt/media/downloads
    type: hostPath
  tv:
    globalMounts:
    - path: /tv
    hostPath: /mnt/media/tv
    type: hostPath
service:
  main:
    controller: main
    ports:
      http:
        port: 8989
