USER-SUPPLIED VALUES:
controllers:
  main:
    containers:
      main:
        env:
          PGID: "1000"
          PUID: "1000"
          TZ: Europe/London
        image:
          repository: linuxserver/jellyfin
          tag: latest
    pod:
      dnsConfig:
        options:
        - name: single-request-reopen
        - name: ndots
          value: "1"
        - name: timeout
          value: "1"
        - name: attempts
          value: "2"
      nodeSelector:
        kubernetes.io/hostname: mbp13-2015
    strategy: Recreate
persistence:
  cache:
    accessMode: ReadWriteOnce
    globalMounts:
    - path: /cache
    size: 10Gi
    storageClass: local-path
    type: persistentVolumeClaim
  config:
    accessMode: ReadWriteOnce
    globalMounts:
    - path: /config
    size: 5Gi
    storageClass: local-path
    type: persistentVolumeClaim
  movie:
    globalMounts:
    - path: /movie
      readOnly: true
    hostPath: /mnt/media/movie
    type: hostPath
  tv:
    globalMounts:
    - path: /tv
      readOnly: true
    hostPath: /mnt/media/tv
    type: hostPath
service:
  main:
    controller: main
    ports:
      http:
        port: 8096
